FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Build args
ARG JWT_SECRET

# Set environment variables from build args
ENV JWT_SECRET=${JWT_SECRET}



# Install dependencies
RUN npm install -g pnpm
RUN pnpm install -r

# 
RUN pnpm run db:generate


# RUN pnpm turbo run build --filter=./apps/server...
RUN pnpm run build-server 


CMD ["pnpm", "run", "start-server"]

