FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml turbo.json ./

COPY apps ./apps
COPY packages ./packages


# Install dependencies
RUN npm install -g pnpm
RUN pnpm install -r

# 
RUN pnpm run db:generate


RUN pnpm turbo run build --filter=./apps/server...


CMD ["pnpm", "run", "start-server"]

